[package]
name = "hours"
version = "0.1.0"
authors = ["Michal 'Koikos' Kozik <mike.koikos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
exitfailure = "0.5.1"
